In [ ]:
!pwd

/content


In [ ]:
cd drive/MyDrive

/content/drive/MyDrive


In [ ]:
pwd

'/content/drive/MyDrive'

In [ ]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# numpy

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.shape, arr.ndim, arr.dtype, arr.itemsize, arr.size
# 형상, 차원, 자료형, 크기, 개수

((10,), 1, dtype('int64'), 8, 10)

In [ ]:
a= np.array([10,20,30])
a *10 #스칼라를 벡터로 확장(브로드캐스팅)

array([100, 200, 300])

In [ ]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a= np.full((3,3),True, dtype=bool) # 초기값 지정
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [ ]:
#연습문제
b = np.eye(4)*10 # 대각선분이 1 나머지 0
b

array([[10.,  0.,  0.,  0.],
       [ 0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.],
       [ 0.,  0.,  0., 10.]])

In [ ]:
arr = np.arange(1,10,2)
# arr
arr[arr%2 ==1]

array([1, 3, 5, 7, 9])

In [ ]:
arr[arr%2 ==1] = -1 #홀수를 모두 -1로
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
arr = np.arange(10)
output = np.where(arr%2==1, -1, arr) # 홀수를 -1로 변경
output

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#연습문제
b= np.array([[1,1],[2,2],[3,3]])
np.insert(b,1,[4,4,4],axis=1) # 인덱스 1번 자리에 axis=1 방향으로 넣기

array([[1, 4, 1],
       [2, 4, 2],
       [3, 4, 3]])

In [ ]:
str_a = [20,30,40]
str_b=[70,80,90]
list_sum = str_a+str_b  #리스트는 배열을 연결해줌줌
list_sum

[20, 30, 40, 70, 80, 90]

In [ ]:
d = np.array([[35,24,55],
              [69,19,9]])
d.flatten() #2차원을 1차원으로 변환

array([35, 24, 55, 69, 19,  9])

In [ ]:
d = np.array([35,24,55])
d.sort() #오름
d[::-1] #내림

array([55, 35, 24])

In [ ]:
#연습문제
d = np.array([[35,24,55],
              [69,19,9],
              [4,1,11]])
d.sort(axis=0) #열을 오름차순(세로)
np.flip(d,axis=0) #열을 뒤집기

array([[69, 24, 55],
       [35, 19, 11],
       [ 4,  1,  9]])

In [ ]:
#연습문제
d = np.array([[35,24,55],
              [69,19,9],
              [4,1,11]])
d.sort(axis=1) # 행을 오름차순(가로)
np.flip(d,axis=1) #행을 뒤집기

array([[55, 35, 24],
       [69, 19,  9],
       [11,  4,  1]])

In [ ]:
#연습문제
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#도전문제(난수)
#np.random.seed(42) 매번 동일한 난수의 열 얻음
def train_test_split(t):
  np.random.shuffle(t) #뒤섞은 값
  r= int(t.size * 0.8)
  train_data = t[:r] # 80%
  test_data = t[r:] # 20%
  return train_data, test_data

a= np.arange(1,51)
train_d, test_d = train_test_split(a)
print("train_data=", train_d)
print("test_data=", test_d)

train_data= [19  5  1 20 44 14 42 36  4 34 25 41 32 45 15 21  9  8 46  7 17 37 26 33
 18 11 48 31 35 50 43  3 47  2 28 30 13 12 40  6]
test_data= [22 10 24 16 29 49 38 27 23 39]


In [ ]:
a = [0,1,2,3,4,5]
a[::] #전체
a[4:2:-1]

[4, 3]

# 벡터화 연산 성능 측정

In [ ]:
import numpy as np
import time

n = 100000
a = np.random.rand(n)
b= np.random.rand(n)
result = np.zeros(n)

#for문사용
start = time.time()
for i in range(n):
  result[i] = a[i] * b[i]
end=time.time()
print('원소별 접근 소요시간: ',end-start)

#벡터화 연산
start = time.time()
result = a*b
end = time.time()
print('벡터화연산 소요시간: ',end-start)

원소별 접근 소요시간:  0.04518699645996094
벡터화연산 소요시간:  0.0009520053863525391


In [ ]:
#리덕션(다차원배열)
import numpy as np
import time

n = 1000
a = np.random.rand(n,n)
sum =0
start = time.time()

#for문
for i in range(n):
  for j in range(n):
    sum += a[i,j]
end=time.time()
print(n,'x',n, '배열 원소 합=',sum, '\n계산시간: ',end-start)

#벡터화 연산
start = time.time()
sum1 = np.sum(a,axis=(0,1))
end=time.time()
print(n,'x',n, '배열 원소 합=',sum1, '\n계산시간: ',end-start)


1000 x 1000 배열 원소 합= 500056.7657628467 
계산시간:  0.2679779529571533
1000 x 1000 배열 원소 합= 500056.76576284936 
계산시간:  0.0030972957611083984
